INSERT INTO fun_facts (fact_text, category) VALUES ('Bangladesh has the longest unbroken sea beach in the world, Cox''s Bazar, stretching 120 km.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('The Royal Bengal Tiger is our national animal and primarily lives in the Sundarbans, the largest mangrove forest on Earth.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Bangladesh has six seasons (Grishma, Barsha, Sharat, Hemanta, Sheet, Basanta) instead of the usual four.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('The National Parliament House (Jatiya Sangsad Bhaban) is one of the largest legislative complexes in the world, designed by Louis I. Kahn.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Hilsa (Ilish) is the national fish of Bangladesh and accounts for about 12% of the country''s total fish production.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Kabadib is the national sport of Bangladesh, though Cricket is the most popular.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('The Magpie Robin (Doel) is the national bird of Bangladesh.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Jackfruit (Kathal) is the national fruit of Bangladesh.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Bangladesh is known as the ''Land of Rivers'' with over 700 rivers flowing through it.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('The Sundarbans is a UNESCO World Heritage Site and home to the last remaining population of mangrove tigers.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Muslin, a legendary lightweight cotton fabric, originated in Dhaka and was valuable worldwide before the industry declined.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Bangladesh is the 8th most populous country in the world.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Mahasthangarh in Bogra is the oldest known city in Bangladesh, dating back to at least the 3rd century BC.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('The Shapla (White Water Lily) is the national flower of Bangladesh.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Bangladesh has the world''s largest river delta, formed by the Ganges, Brahmaputra, and Meghna rivers.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Nakshi Kantha is a centuries-old tradition of making embroidered quilts from old saris.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Pohela Boishakh, the Bengali New Year, involves the colorful ''Mangal Shobhajatra'' parade, recognized by UNESCO.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Rickshaws in Dhaka are famous for their colorful art and are recognized as Intangible Cultural Heritage by UNESCO.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Sylhet is known as the ''Land of Two Leaves and a Bud'' due to its vast tea gardens.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Saint Martin''s Island is the only coral island in Bangladesh.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Bagerhat is known as the ''City of Mosques'' and hosts the historic Sixty Dome Mosque.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('The Jamuna Bridge (Bangabandhu Bridge) is one of the longest bridges in South Asia.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Bangladesh is a top exporter of ready-made garments (RMG) worldwide.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('The Doyel Chatwar in Dhaka features a giant statue of the national bird, the Magpie Robin.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Language Movement Day (February 21st) is celebrated globally as International Mother Language Day.', 'Bangladesh');
INSERT INTO fun_facts (fact_text, category) VALUES ('Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Bananas are botanically classified as berries, while strawberries are not.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Octopuses have three hearts and blue blood.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('A day on Venus is longer than a year on Venus. It rotates very slowly.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of the iron.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Wombat poop is cube-shaped, which stops it from rolling away.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Avocados were named after the Aztec word for ''testicle'' because of their shape.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('A group of flamingos is called a ''flamboyance''.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Bangkok''s full ceremonial name is the longest city name in the world, with 168 letters.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Human teeth are the only part of the body that cannot heal themselves.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('It is physically impossible for pigs to look up into the sky.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('A cloud can weigh more than a million pounds.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('The Great Wall of China is not visible from space with the naked eye, contrary to popular myth.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Cows have best friends and get stressed when they are distinguishable.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('There are more stars in the universe than grains of sand on all the Earth''s beaches.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Sea otters hold hands when they sleep to keep from drifting apart.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('The unicorn is the national animal of Scotland.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Humans share about 60% of their DNA with bananas.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('A bolt of lightning contains enough energy to toast 100,000 slices of bread.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('The inventor of the Pringles can is now buried in one.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Water makes up about 71% of the Earth''s surface, but vast majority of it is salt water.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('Sharks have existed for longer than trees.', 'Global');
INSERT INTO fun_facts (fact_text, category) VALUES ('There is a species of jellyfish (Turritopsis dohrnii) that is biologically immortal.', 'Global');